on:
  pull_request:
    types: [opened, synchronize, edited]
  push:
    branches:
      - "main"

name: Run Pytest for API

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Set up Python 🐍
        uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
        with:
          python-version: "3.11"

      - name: Install Poetry 💈
        run: pip install poetry

      - name: Prepare
        run: |
          cd api
          poetry install
          openssl genrsa -out demo_key_private.pem 2048

      - name: Run tests
        run: |
          cd api
          poetry run pytest --runslow
